### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined while generating report in report folder

### ISSUE THREAD

**Issue by Harsh-BBC** [wswebcreation/wdio-multiple-cucumber-html-reporter#20]
**Environment (please complete the following information):**
 - Node.js version: [e.g. 10.10.0]
 - NPM version: [e.g. 6.4.1]
 - webdriver.io version: [e.g. 4.14.1]
 - wdio-cucumber-framework version: [e.g. 2.2.8 (if lower this module will not work as it should be)]
 - wdio-multiple-cucumber-html-reporter version: [e.g. 0.3.3]

**Config of webdriver.io and the reporter**
#wdio.config.js
```js
reporters: ['multiple-cucumber-html'],
  reporterOptions: {
    htmlReporter: {
      jsonFolder: rootPath + 'reports/',
      reportFolder: `${rootPath}`
    }
  },
```
#package.json
```js
"devDependencies": {
        "chai": "^4.2.0",
        "cucumber": "^5.0.2",
        "wdio-cucumber-framework": "^2.2.8",
        "webdriverio": "^4.14.1",
        "wdio-allure-reporter": "^0.8.3",
        "allure-commandline": "^2.8.1",
        "wdio-spec-reporter": "^0.1.5",
        "wdio-json-reporter":"^0.4.0",
        "wdio-multiple-cucumber-html-reporter": "^0.3.3"
   
}
```

**Describe the bug**
I am able to see json file generated after running the tests but while generating html report it gives this error

```shell
path_to_repo/node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (lodash.templateSources[1]:205:76)
    at arrayEach (path_to_repo/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (path_to_repo/node_modules/lodash/lodash.js:9344:14)
    at eval (lodash.templateSources[1]:38:4)
    at _createFeaturesOverviewIndexPage (/path_to_repo/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:449:84)
    at generateReport (path_to_repo/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:135:3)
    at MultipleCucumberHtmlReporter.onEnd (path_to_repo/node_modules/wdio-multiple-cucumber-html-reporter/build/reporter.js:160:56)
    at MultipleCucumberHtmlReporter.emit (events.js:182:13)
    at MultipleCucumberHtmlReporter.EventEmitter.emit (domain.js:442:20)
    at BaseReporter.handleEvent (path_to_repo/node_modules/webdriverio/build/lib/util/BaseReporter.js:324:35)`
```

**To Reproduce**

Add reporter in conf.js and run "npm run script_name"

**Expected behavior**
HTML report should get generated

**Comment by wswebcreation** [comment]
@Harsh-BBC 

🤦‍♂️ never saw this issue, my bad. Is this still happening?

Can you also provide your `capabilities` object?

**Comment by wswebcreation** [comment]
Closing this in favour of https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter/issues/24
